### ISSUE TITLE
Local Subtitle

### ISSUE THREAD

**Issue by sinadalvand** [halilozercan/BetterVideoPlayer#46]
hi 

i use this library and i need complete app for next 2 day

i want to use local subtitle in video player how i must do this?

**Comment by Yacovmm** [comment]
I think u can do that, because it's only implemented by the raw files.
Apparently he not implemented this feature because it would be some issues with the user permissions...

**Comment by sinadalvand** [comment]
thanks for answer 

i added button to toolbar can choose subtitle from locale storage and add that to player 

if you like share edited library whit you ?!

**Comment by halilozercan** [comment]
> I think u can't do that, because it's only implemented by the raw files.
Apparently he not implemented this feature because it would be some issues with the user permissions...

Due to my busy schedule, I'm not able to answer some questions properly. Back in the day, I thought about adding support for local subtitles but wasn't sure about how to implement file storage permissions. Either library would request the necessary permission or the app would handle such a case. However, now I think it was programmer's job to handle such cases. 

I would gladly merge a pull request that implements loading subtitles from local storage in which "read permissions" are supposed to be granted already.

**Comment by Yacovmm** [comment]
@sinadalvand  I would love to have it, it would be very useful and great to me if u could share it with me

**Comment by sinadalvand** [comment]
@Yacovmm i don't know how use git to share this edited library , do you know another way ? 
do you have telegram account ?

**Comment by Yacovmm** [comment]
Yes @sinadalvand, I have a telegram account, my nick-name is @yacovmm
reach me there:)
